//! How much two images may differ and still match.

// The serde derive generates an empty field enum for the empty `Exact {}` struct variant.
#![expect(
    clippy::empty_enums,
    reason = "generated by the serde derive for `Tolerance::Exact {}`"
)]

use gleon_engine::config::{DiffConfig, Mode};
use serde::{Deserialize, Serialize};

/// A [`Tolerance`] parameter outside its range.
#[derive(Debug, Clone, Copy, PartialEq, thiserror::Error)]
pub enum ToleranceError {
    /// A ratio outside `[0, 1]`.
    #[error("`{name}` must be between 0.0 and 1.0 (got {value})")]
    Ratio {
        /// Parameter name (`max_diff_ratio` or `min_similarity`).
        name: &'static str,
        /// The rejected value.
        value: f64,
    },
    /// A `color_tolerance` outside `[0, 255]` (NaN included).
    #[error("`color_tolerance` must be between 0 and 255 (got {0})")]
    ColorTolerance(f64),
}

/// Comparison tolerance.
///
/// Each mode carries only its own parameters, so a parameter of another mode is unrepresentable.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Tolerance {
    /// Every pixel must be identical (the Flutter SDK default).
    // An empty struct variant, not a unit variant, so `deny_unknown_fields` also rejects
    // parameters of other modes here.
    Exact {},
    /// Tolerates a fraction of differing pixels.
    Pixel {
        /// Largest tolerated fraction of differing pixels, `[0, 1]`.
        #[schemars(range(min = 0.0, max = 1.0))]
        max_diff_ratio: f64,
    },
    /// Tolerates rendering noise under the engine's SSIM policy.
    Ssim {
        /// Minimum local SSIM `[0, 1]` every neighborhood must reach.
        #[schemars(range(min = 0.0, max = 1.0))]
        min_similarity: f64,
        /// Tolerated deviation beyond the local envelope, in 8-bit channel units.
        #[schemars(range(min = 0.0))]
        color_tolerance: f64,
    },
}

impl Tolerance {
    /// The tolerance a `gleon.yaml` screenshot rule describes (`anti_alias` is not used by the
    /// engine and has no counterpart).
    #[must_use]
    pub const fn from_rule(mode: Mode, diff: &DiffConfig) -> Self {
        match mode {
            Mode::Pixel => Self::Pixel {
                max_diff_ratio: diff.threshold,
            },
            Mode::Ssim => Self::Ssim {
                min_similarity: diff.min_similarity,
                color_tolerance: diff.color_tolerance,
            },
        }
    }

    /// Checks value ranges that serde cannot express.
    ///
    /// # Errors
    /// Returns [`ToleranceError::Ratio`] if a ratio is outside `[0, 1]` (NaN included) or
    /// [`ToleranceError::ColorTolerance`] if `color_tolerance` is outside `[0, 255]`.
    pub fn validate(&self) -> Result<(), ToleranceError> {
        let ratio = |name: &'static str, value: f64| {
            if (0.0..=1.0).contains(&value) {
                Ok(())
            } else {
                Err(ToleranceError::Ratio { name, value })
            }
        };
        match *self {
            Self::Exact {} => Ok(()),
            Self::Pixel { max_diff_ratio } => ratio("max_diff_ratio", max_diff_ratio),
            Self::Ssim {
                min_similarity,
                color_tolerance,
            } => ratio("min_similarity", min_similarity).and_then(|()| {
                if gleon_engine::config::is_valid_color_tolerance(color_tolerance) {
                    Ok(())
                } else {
                    Err(ToleranceError::ColorTolerance(color_tolerance))
                }
            }),
        }
    }

    /// The engine mode and configuration implementing this tolerance (exact is pixel mode with a
    /// zero threshold).
    #[must_use]
    pub fn engine_config(&self) -> (Mode, DiffConfig) {
        let base = DiffConfig::default();
        match *self {
            Self::Exact {} => (
                Mode::Pixel,
                DiffConfig {
                    threshold: 0.0,
                    ..base
                },
            ),
            Self::Pixel { max_diff_ratio } => (
                Mode::Pixel,
                DiffConfig {
                    threshold: max_diff_ratio,
                    ..base
                },
            ),
            Self::Ssim {
                min_similarity,
                color_tolerance,
            } => (
                Mode::Ssim,
                DiffConfig {
                    min_similarity,
                    color_tolerance,
                    ..base
                },
            ),
        }
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::float_cmp,
    clippy::pedantic,
    clippy::nursery,
    reason = "test code: panics are assertions, and pedantic/nursery style lints are not enforced in tests"
)]
mod tests {
    use super::*;

    #[test]
    fn test_json_is_internally_tagged_and_strict() {
        let ssim: Tolerance =
            serde_json::from_str(r#"{"kind":"ssim","min_similarity":0.9,"color_tolerance":8}"#)
                .unwrap();
        assert_eq!(
            ssim,
            Tolerance::Ssim {
                min_similarity: 0.9,
                color_tolerance: 8.0
            }
        );
        assert_eq!(
            serde_json::to_string(&Tolerance::Exact {}).unwrap(),
            r#"{"kind":"exact"}"#
        );
        for bad in [
            r#"{"kind":"exact","max_diff_ratio":0.1}"#,
            r#"{"kind":"pixel"}"#,
            r#"{"kind":"pixel","max_diff_ratio":0.1,"color_tolerance":8}"#,
            r#"{"kind":"ssim","min_similarity":0.9}"#,
            r#"{"kind":"fuzzy"}"#,
        ] {
            assert!(serde_json::from_str::<Tolerance>(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn test_validate_ranges() {
        assert!(Tolerance::Exact {}.validate().is_ok());
        let pixel = Tolerance::Pixel {
            max_diff_ratio: 1.5,
        };
        assert_eq!(
            pixel.validate(),
            Err(ToleranceError::Ratio {
                name: "max_diff_ratio",
                value: 1.5
            })
        );
        assert_eq!(
            pixel.validate().unwrap_err().to_string(),
            "`max_diff_ratio` must be between 0.0 and 1.0 (got 1.5)"
        );
        let ssim = |min_similarity, color_tolerance| Tolerance::Ssim {
            min_similarity,
            color_tolerance,
        };
        assert!(ssim(0.8, 8.0).validate().is_ok());
        for bad in [-0.1, f64::NAN] {
            assert!(matches!(
                ssim(bad, 8.0).validate(),
                Err(ToleranceError::Ratio {
                    name: "min_similarity",
                    ..
                })
            ));
        }
        for bad in [-1.0, 255.5, f64::NAN, f64::INFINITY] {
            assert!(matches!(
                ssim(0.8, bad).validate(),
                Err(ToleranceError::ColorTolerance(_))
            ));
        }
        assert!(ssim(0.8, 255.0).validate().is_ok());
    }

    #[test]
    fn test_rule_and_engine_round_trip() {
        let diff = DiffConfig {
            threshold: 0.05,
            min_similarity: 0.7,
            color_tolerance: 12.0,
            ..DiffConfig::default()
        };
        let pixel = Tolerance::from_rule(Mode::Pixel, &diff);
        assert_eq!(
            pixel,
            Tolerance::Pixel {
                max_diff_ratio: 0.05
            }
        );
        assert_eq!(pixel.engine_config().1.threshold, 0.05);

        let ssim = Tolerance::from_rule(Mode::Ssim, &diff);
        let (mode, config) = ssim.engine_config();
        assert_eq!(mode, Mode::Ssim);
        assert_eq!((config.min_similarity, config.color_tolerance), (0.7, 12.0));

        let (mode, config) = Tolerance::Exact {}.engine_config();
        assert_eq!((mode, config.threshold), (Mode::Pixel, 0.0));
    }
}
