//! How much two images may differ and still match.

// The serde derive generates an empty field enum for the empty `Exact {}` struct variant.
#![expect(
    clippy::empty_enums,
    reason = "generated by the serde derive for `Tolerance::Exact {}`"
)]

use gleon_engine::{
    PixelOptions,
    config::{DiffConfig, Mode},
};
use serde::{Deserialize, Serialize};

/// A [`Tolerance`] parameter outside its range.
#[derive(Debug, Clone, Copy, PartialEq, thiserror::Error)]
pub enum ToleranceError {
    /// A ratio outside `[0, 1]`.
    #[error("`{name}` must be between 0.0 and 1.0 (got {value})")]
    Ratio {
        /// Parameter name (`max_diff_ratio`, `min_similarity` or `text_tolerance`).
        name: &'static str,
        /// The rejected value.
        value: f64,
    },
    /// A `color_tolerance` outside `[0, 255]` (NaN included).
    #[error("`color_tolerance` must be between 0 and 255 (got {0})")]
    ColorTolerance(f64),
    /// A pixel option above [`gleon_engine::config::MAX_PIXEL_OPTION`].
    #[error("`{name}` must be between 0 and 254 (got {value})")]
    PixelOption {
        /// Option name (`channel_tolerance` or `edge_threshold`).
        name: &'static str,
        /// The rejected value.
        value: u8,
    },
}

/// Comparison tolerance.
///
/// Each mode carries only its own parameters, so a parameter of another mode is unrepresentable.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Tolerance {
    /// Every pixel must be identical (the Flutter SDK default).
    // An empty struct variant, not a unit variant, so `deny_unknown_fields` also rejects
    // parameters of other modes here.
    Exact {},
    /// Tolerates a fraction of differing pixels, and differing pixels its options let pass.
    Pixel {
        /// Largest tolerated fraction of differing pixels, `[0, 1]`.
        #[schemars(range(min = 0.0, max = 1.0))]
        max_diff_ratio: f64,
        /// A differing pixel outside text counts as equal when no RGBA byte differs by more than
        /// this, `[0, 254]` (0: off).
        #[serde(default, skip_serializing_if = "crate::serde_skip::is_default")]
        #[schemars(range(max = 254))]
        channel_tolerance: u8,
        /// A differing pixel outside text counts as equal when it looks anti-aliased in either
        /// image.
        #[serde(default, skip_serializing_if = "crate::serde_skip::is_default")]
        anti_alias: bool,
        /// A differing pixel outside text counts as equal when the Sobel gradient of the golden's
        /// luma there (unnormalized like Skia Gold's: a sharp step of 16 gives 64) exceeds this,
        /// `[0, 254]` (0: off).
        #[serde(default, skip_serializing_if = "crate::serde_skip::is_default")]
        #[schemars(range(max = 254))]
        edge_threshold: u8,
    },
    /// Tolerates rendering noise under the engine's SSIM policy.
    Ssim {
        /// Minimum local SSIM `[0, 1]` every neighborhood must reach.
        #[schemars(range(min = 0.0, max = 1.0))]
        min_similarity: f64,
        /// Tolerated deviation beyond the local envelope, in 8-bit channel units, `[0, 255]`.
        #[schemars(range(min = 0.0, max = 255.0))]
        color_tolerance: f64,
    },
}

impl Tolerance {
    /// A pixel tolerance of `max_diff_ratio` without options: every differing pixel counts.
    #[must_use]
    pub const fn pixel(max_diff_ratio: f64) -> Self {
        Self::Pixel {
            max_diff_ratio,
            channel_tolerance: 0,
            anti_alias: false,
            edge_threshold: 0,
        }
    }

    /// The tolerance a `gleon.yaml` screenshot rule describes.
    #[must_use]
    pub const fn from_rule(mode: Mode, diff: &DiffConfig) -> Self {
        match mode {
            Mode::Pixel => Self::Pixel {
                max_diff_ratio: diff.threshold,
                channel_tolerance: diff.channel_tolerance,
                anti_alias: diff.anti_alias,
                edge_threshold: diff.edge_threshold,
            },
            Mode::Ssim => Self::Ssim {
                min_similarity: diff.min_similarity,
                color_tolerance: diff.color_tolerance,
            },
        }
        .without_negative_zero()
    }

    /// `self` with `-0.0` parameters as `0.0`: both are valid and compare equal, but `-0.0` would
    /// show up in case reports.
    #[must_use]
    pub const fn without_negative_zero(self) -> Self {
        // `-0.0 + 0.0` is `0.0`; every other value (NaN included) stays as it is.
        const fn positive_zero(value: f64) -> f64 {
            value + 0.0
        }
        match self {
            Self::Exact {} => Self::Exact {},
            Self::Pixel {
                max_diff_ratio,
                channel_tolerance,
                anti_alias,
                edge_threshold,
            } => Self::Pixel {
                max_diff_ratio: positive_zero(max_diff_ratio),
                channel_tolerance,
                anti_alias,
                edge_threshold,
            },
            Self::Ssim {
                min_similarity,
                color_tolerance,
            } => Self::Ssim {
                min_similarity: positive_zero(min_similarity),
                color_tolerance: positive_zero(color_tolerance),
            },
        }
    }

    /// Checks value ranges that serde cannot express.
    ///
    /// # Errors
    /// Returns [`ToleranceError::Ratio`] if a ratio is outside `[0, 1]` (NaN included) or
    /// [`ToleranceError::ColorTolerance`] if `color_tolerance` is outside `[0, 255]`.
    pub fn validate(&self) -> Result<(), ToleranceError> {
        let ratio = |name: &'static str, value: f64| {
            if (0.0..=1.0).contains(&value) {
                Ok(())
            } else {
                Err(ToleranceError::Ratio { name, value })
            }
        };
        match *self {
            Self::Exact {} => Ok(()),
            Self::Pixel {
                max_diff_ratio,
                channel_tolerance,
                edge_threshold,
                ..
            } => {
                let option = |name, value| {
                    if value <= gleon_engine::config::MAX_PIXEL_OPTION {
                        Ok(())
                    } else {
                        Err(ToleranceError::PixelOption { name, value })
                    }
                };
                ratio("max_diff_ratio", max_diff_ratio)
                    .and_then(|()| option("channel_tolerance", channel_tolerance))
                    .and_then(|()| option("edge_threshold", edge_threshold))
            }
            Self::Ssim {
                min_similarity,
                color_tolerance,
            } => ratio("min_similarity", min_similarity).and_then(|()| {
                if gleon_engine::config::is_valid_color_tolerance(color_tolerance) {
                    Ok(())
                } else {
                    Err(ToleranceError::ColorTolerance(color_tolerance))
                }
            }),
        }
    }

    /// The largest share of differing pixels a pixel comparison allows: exact is a zero
    /// threshold (and so is SSIM, which has none).
    #[must_use]
    pub const fn max_diff_ratio(&self) -> f64 {
        match *self {
            Self::Pixel { max_diff_ratio, .. } => max_diff_ratio,
            Self::Exact {} | Self::Ssim { .. } => 0.0,
        }
    }

    /// The differing pixels a pixel comparison lets pass ([`PixelOptions::STRICT`] for exact and
    /// SSIM).
    #[must_use]
    pub const fn pixel_options(&self) -> PixelOptions {
        match *self {
            Self::Pixel {
                channel_tolerance,
                anti_alias,
                edge_threshold,
                ..
            } => PixelOptions {
                channel_tolerance,
                anti_alias,
                edge_threshold,
            },
            Self::Exact {} | Self::Ssim { .. } => PixelOptions::STRICT,
        }
    }

    /// The engine mode and configuration implementing this tolerance (exact is pixel mode with a
    /// zero threshold).
    #[must_use]
    pub fn engine_config(&self) -> (Mode, DiffConfig) {
        let base = DiffConfig::default();
        match *self {
            Self::Exact {} | Self::Pixel { .. } => {
                let options = self.pixel_options();
                (
                    Mode::Pixel,
                    DiffConfig {
                        threshold: self.max_diff_ratio(),
                        channel_tolerance: options.channel_tolerance,
                        anti_alias: options.anti_alias,
                        edge_threshold: options.edge_threshold,
                        ..base
                    },
                )
            }
            Self::Ssim {
                min_similarity,
                color_tolerance,
            } => (
                Mode::Ssim,
                DiffConfig {
                    min_similarity,
                    color_tolerance,
                    ..base
                },
            ),
        }
    }
}

/// How much text may differ, under any [`Tolerance`].
///
/// The largest share (`[0, 1]`) of differing pixels in any [`gleon_engine::pixel::TEXT_TILE`]-pixel
/// tile of the text regions an integration reports (lines of its render tree); everything else
/// is compared under the tolerance (in SSIM mode the text is left out of both of its gates), and
/// no pixel option applies to text.
///
/// Operating systems draw glyphs differently (their font engines, hinting): across them 40% or
/// more of a tile of text differs while a changed digit of the same width is about a quarter, so
/// no share tells them apart. [`Self::DEFAULT`] (1) lets text never fail, which is the same verdict as
/// masking it: the layout is compared, text content is not. Lower values compare text, at the
/// risk of failing on another OS's rendering. Against a golden of the platform it runs on, the
/// default is [`Self::OWN_PLATFORM`] instead (see [`Self::resolve`]).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(transparent)]
pub struct TextTolerance(#[schemars(range(min = 0.0, max = 1.0))] pub f64);

impl TextTolerance {
    /// The tolerance of text an integration reports without one from its call or rule, against a
    /// golden of another (or an unknown) platform: text never fails.
    pub const DEFAULT: Self = Self(1.0);

    /// The default tolerance of text against a golden of the platform it is compared on: one OS draws
    /// the same glyphs the same way give or take a pixel per tile across its versions (macOS 15
    /// against goldens of macOS 26: 1 of 256), while a changed digit is about a quarter.
    pub const OWN_PLATFORM: Self = Self(0.05);

    /// The tolerance a comparison uses: the `explicit` one (the integration call's, else the
    /// `.gleon/gleon.yaml` rule's), else the default of the golden: [`Self::OWN_PLATFORM`] for a
    /// golden of the platform it is compared on (`is_own_platform`), [`Self::DEFAULT`] for any
    /// other. An explicit value always applies, so `1` turns text comparison off on the golden's
    /// platform too.
    #[must_use]
    pub const fn resolve(explicit: Option<Self>, is_own_platform: bool) -> Self {
        match explicit {
            Some(explicit) => explicit,
            None if is_own_platform => Self::OWN_PLATFORM,
            None => Self::DEFAULT,
        }
    }

    /// Checks the value range.
    ///
    /// # Errors
    /// Returns [`ToleranceError::Ratio`] if the share is outside `[0, 1]` (NaN included).
    pub fn validate(&self) -> Result<(), ToleranceError> {
        if (0.0..=1.0).contains(&self.0) {
            Ok(())
        } else {
            Err(ToleranceError::Ratio {
                name: "text_tolerance",
                value: self.0,
            })
        }
    }

    /// `self` with `-0.0` as `0.0`, like [`Tolerance::without_negative_zero`].
    #[must_use]
    pub const fn without_negative_zero(self) -> Self {
        // `-0.0 + 0.0` is `0.0`; every other value (NaN included) stays as it is.
        Self(self.0 + 0.0)
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::float_cmp,
    clippy::pedantic,
    clippy::nursery,
    reason = "test code: panics are assertions, and pedantic/nursery style lints are not enforced in tests"
)]
mod tests {
    use super::*;

    #[test]
    fn test_json_is_internally_tagged_and_strict() {
        let ssim: Tolerance =
            serde_json::from_str(r#"{"kind":"ssim","min_similarity":0.9,"color_tolerance":8}"#)
                .unwrap();
        assert_eq!(
            ssim,
            Tolerance::Ssim {
                min_similarity: 0.9,
                color_tolerance: 8.0
            }
        );
        assert_eq!(
            serde_json::to_string(&Tolerance::Exact {}).unwrap(),
            r#"{"kind":"exact"}"#
        );
        for bad in [
            r#"{"kind":"exact","max_diff_ratio":0.1}"#,
            r#"{"kind":"pixel"}"#,
            r#"{"kind":"pixel","max_diff_ratio":0.1,"color_tolerance":8}"#,
            r#"{"kind":"ssim","min_similarity":0.9}"#,
            r#"{"kind":"fuzzy"}"#,
        ] {
            assert!(serde_json::from_str::<Tolerance>(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn test_validate_ranges() {
        assert!(Tolerance::Exact {}.validate().is_ok());
        let pixel = Tolerance::pixel(1.5);
        assert_eq!(
            pixel.validate(),
            Err(ToleranceError::Ratio {
                name: "max_diff_ratio",
                value: 1.5
            })
        );
        assert_eq!(
            pixel.validate().unwrap_err().to_string(),
            "`max_diff_ratio` must be between 0.0 and 1.0 (got 1.5)"
        );
        let ssim = |min_similarity, color_tolerance| Tolerance::Ssim {
            min_similarity,
            color_tolerance,
        };
        assert!(ssim(0.8, 8.0).validate().is_ok());
        for bad in [-0.1, f64::NAN] {
            assert!(matches!(
                ssim(bad, 8.0).validate(),
                Err(ToleranceError::Ratio {
                    name: "min_similarity",
                    ..
                })
            ));
        }
        for bad in [-1.0, 255.5, f64::NAN, f64::INFINITY] {
            assert!(matches!(
                ssim(0.8, bad).validate(),
                Err(ToleranceError::ColorTolerance(_))
            ));
        }
        assert!(ssim(0.8, 255.0).validate().is_ok());

        for good in [0.0, 0.1, 1.0] {
            assert!(TextTolerance(good).validate().is_ok(), "{good}");
        }
        for bad in [-0.1, 1.5, f64::NAN, f64::INFINITY] {
            assert!(matches!(
                TextTolerance(bad).validate(),
                Err(ToleranceError::Ratio {
                    name: "text_tolerance",
                    ..
                })
            ));
        }
    }

    #[test]
    fn test_validate_rejects_pixel_options_of_255() {
        let options = |channel_tolerance, edge_threshold| Tolerance::Pixel {
            max_diff_ratio: 0.0,
            channel_tolerance,
            anti_alias: false,
            edge_threshold,
        };
        assert!(options(254, 254).validate().is_ok());
        assert_eq!(
            options(255, 0).validate(),
            Err(ToleranceError::PixelOption {
                name: "channel_tolerance",
                value: 255
            })
        );
        assert_eq!(
            options(0, 255).validate().unwrap_err().to_string(),
            "`edge_threshold` must be between 0 and 254 (got 255)"
        );
    }

    #[test]
    fn test_rule_and_engine_round_trip() {
        let diff = DiffConfig {
            threshold: 0.05,
            min_similarity: 0.7,
            color_tolerance: 12.0,
            channel_tolerance: 4,
            anti_alias: true,
            edge_threshold: 64,
        };
        let pixel = Tolerance::from_rule(Mode::Pixel, &diff);
        assert_eq!(
            pixel,
            Tolerance::Pixel {
                max_diff_ratio: 0.05,
                channel_tolerance: 4,
                anti_alias: true,
                edge_threshold: 64,
            }
        );
        let (_, config) = pixel.engine_config();
        assert_eq!(
            (
                config.threshold,
                config.channel_tolerance,
                config.anti_alias,
                config.edge_threshold
            ),
            (0.05, 4, true, 64)
        );
        // Options are left out of reports while off, and default when parsed.
        assert_eq!(
            serde_json::to_string(&Tolerance::pixel(0.01)).unwrap(),
            r#"{"kind":"pixel","max_diff_ratio":0.01}"#
        );
        assert_eq!(
            serde_json::to_string(&pixel).unwrap(),
            r#"{"kind":"pixel","max_diff_ratio":0.05,"channel_tolerance":4,"anti_alias":true,"edge_threshold":64}"#
        );
        assert_eq!(
            serde_json::from_str::<Tolerance>(r#"{"kind":"pixel","max_diff_ratio":0.01}"#).unwrap(),
            Tolerance::pixel(0.01)
        );
        assert_eq!(
            Tolerance::Ssim {
                min_similarity: 0.8,
                color_tolerance: 8.0
            }
            .pixel_options(),
            PixelOptions::STRICT
        );

        let ssim = Tolerance::from_rule(Mode::Ssim, &diff);
        let (mode, config) = ssim.engine_config();
        assert_eq!(mode, Mode::Ssim);
        assert_eq!((config.min_similarity, config.color_tolerance), (0.7, 12.0));

        let (mode, config) = Tolerance::Exact {}.engine_config();
        assert_eq!((mode, config.threshold), (Mode::Pixel, 0.0));
    }

    #[test]
    fn test_negative_zero_becomes_zero() {
        let zeros = DiffConfig {
            threshold: -0.0,
            min_similarity: -0.0,
            color_tolerance: -0.0,
            ..DiffConfig::default()
        };
        assert!(matches!(
            Tolerance::from_rule(Mode::Pixel, &zeros),
            Tolerance::Pixel { max_diff_ratio, .. } if max_diff_ratio.is_sign_positive()
        ));
        assert_eq!(
            serde_json::to_string(&Tolerance::from_rule(Mode::Ssim, &zeros)).unwrap(),
            r#"{"kind":"ssim","min_similarity":0.0,"color_tolerance":0.0}"#
        );
        assert_eq!(
            serde_json::to_string(&TextTolerance(-0.0).without_negative_zero()).unwrap(),
            "0.0"
        );
        let explicit = TextTolerance(0.2);
        for is_own in [false, true] {
            assert_eq!(TextTolerance::resolve(Some(explicit), is_own), explicit);
        }
        assert_eq!(TextTolerance::resolve(None, false), TextTolerance::DEFAULT);
        assert_eq!(
            TextTolerance::resolve(None, true),
            TextTolerance::OWN_PLATFORM
        );
        assert_eq!(
            TextTolerance::resolve(Some(TextTolerance::DEFAULT), true),
            TextTolerance::DEFAULT,
            "an explicit 1 turns text off on the golden's platform too"
        );
        let kept = Tolerance::Ssim {
            min_similarity: -0.5,
            color_tolerance: 3.0,
        };
        assert_eq!(kept.without_negative_zero(), kept);
        assert_eq!(
            Tolerance::Exact {}.without_negative_zero(),
            Tolerance::Exact {}
        );
    }
}
