//! Generates HTML, `JUnit` XML, and Markdown reports from the case reports of a run
//! ([`crate::cases::Cases`]).
//!
//! Split by output format across private submodules: `html` (`report.html`), `xml`
//! (`junit.xml`), and `markdown` (PR-comment/summary Markdown), plus `presign` (signing remote
//! storage URLs for a Markdown PR comment's baselines), sharing the path and outcome formatting
//! helpers in `format` and the bundled-template registry defined here. Each submodule contributes
//! its generator methods via its own `impl ReportGenerator` block.

mod format;
mod html;
mod markdown;
mod presign;
mod xml;

use std::sync::LazyLock;

use crate::{cases::Cases, manifest::ImageHash};

pub(crate) static JINJA_ENV: LazyLock<minijinja::Environment<'static>> = LazyLock::new(|| {
    let mut env = minijinja::Environment::new();
    for (name, source) in [
        ("report.html", include_str!("../templates/report.html")),
        ("junit.xml", include_str!("../templates/junit.xml")),
        ("pr_comment.md", include_str!("../templates/pr_comment.md")),
        (
            "dashboard.html",
            include_str!("../templates/dashboard.html"),
        ),
    ] {
        // Bundled templates are compiled into the binary and validated by the test suite; a
        // syntax error here would be a build-time bug caught immediately, not a runtime
        // condition callers need to handle.
        #[expect(
            clippy::expect_used,
            reason = "bundled templates are compile-time assets validated by the test suite"
        )]
        env.add_template(name, source)
            .expect("bundled templates are valid minijinja syntax");
    }
    env
});

/// Errors that can occur during report generation.
#[derive(Debug, thiserror::Error)]
pub enum ReportError {
    /// Template rendering failed.
    #[error("Template rendering failed for '{template}'")]
    Render {
        /// Name of the template that failed.
        template: &'static str,
        /// The underlying minijinja error message.
        #[source]
        source: minijinja::Error,
    },

    /// IO error.
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

/// Resolves a baseline (a content-addressed blob) to a signed URL for embedding in a PR comment.
///
/// Returns `None` to fall back to a `base_image_url` link (or `N/A` if that is also unset).
pub type ImageUrlResolver<'a> = dyn Fn(&ImageHash) -> Option<String> + Sync + 'a;

/// Where the PR comment is being rendered, used to pick an appropriate footer.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum RenderTarget {
    /// Rendered for a local terminal invocation (e.g. `gleon diff`).
    #[default]
    LocalTerminal,
    /// Rendered for a GitHub Actions workflow run.
    GitHubActions,
}

/// Options controlling how [`ReportGenerator::render_pr_comment`] links images and
/// which footer it appends.
#[derive(Default)]
pub struct MarkdownReportOptions<'a> {
    /// Public URL of the remote storage, under which baselines live at `blobs/<scheme>/<value>`;
    /// used when no `image_url_resolver` applies.
    pub base_image_url: Option<&'a str>,
    /// URL of the full HTML report artifact, linked when rows are truncated.
    pub html_artifact_url: Option<&'a str>,
    /// Optional resolver of signed baseline URLs, tried before `base_image_url`.
    pub image_url_resolver: Option<&'a ImageUrlResolver<'a>>,
    /// Where the comment is being rendered, selecting the footer text.
    pub context: RenderTarget,
}

/// Generates HTML, `JUnit` XML, and Markdown reports from test results.
pub struct ReportGenerator;

impl ReportGenerator {
    /// Footer appended to PR comments rendered for GitHub Actions.
    pub const FOOTER_GITHUB_ACTIONS: &'static str = "\n---\n*Reply with `/gleon approve` to update baseline images for this PR (see repository README for workflow setup instructions).*\n";
    /// Footer appended to PR comments rendered for a local terminal.
    pub const FOOTER_LOCAL_TERMINAL: &'static str =
        "\n---\n*Run `gleon approve` to accept failed screenshots as new baselines locally.*\n";

    /// The files [`Self::generate_all`] writes into a runs directory.
    pub const OUTPUT_FILES: [&'static str; 3] = ["report.md", "junit.xml", "report.html"];

    /// Generates the markdown, `JUnit` XML and HTML reports of `cases` inside `runs_dir`
    /// ([`Self::OUTPUT_FILES`]); without failures there is no HTML report.
    ///
    /// # Errors
    ///
    /// Returns `ReportError` if any of the underlying report generation steps
    /// fail (template rendering) or if writing a report file to `runs_dir`
    /// fails.
    pub fn generate_all(runs_dir: &std::path::Path, cases: &Cases) -> Result<(), ReportError> {
        // Regenerated by every run: atomic, without the cost of a flush to disk.
        let write = |name: &str, content: &str| {
            gleon_model::fs::write_atomically(
                &runs_dir.join(name),
                content.as_bytes(),
                gleon_model::fs::Durability::Atomic,
            )
        };
        let [md_name, xml_name, html_name] = Self::OUTPUT_FILES;
        write(md_name, &Self::generate_markdown(cases))?;
        write(xml_name, &Self::generate_junit_xml(cases)?)?;
        if let Some(html) = Self::generate_html(cases, runs_dir)? {
            write(html_name, &html)?;
        } else {
            match std::fs::remove_file(runs_dir.join(html_name)) {
                Ok(()) => {}
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(ReportError::Io(e)),
            }
        }
        Ok(())
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::pedantic,
    clippy::nursery,
    reason = "test code: panics are assertions, and pedantic/nursery style lints are not enforced in tests"
)]
mod tests {
    use super::*;

    #[test]
    fn test_report_error_display() {
        let report_err = ReportError::Io(std::io::Error::other("test io"));
        assert_eq!(report_err.to_string(), "IO error: test io");
    }

    #[test]
    fn test_generate_all_removes_stale_report_html_when_no_diffs() {
        let temp = tempfile::tempdir().unwrap();
        let runs_dir = temp.path();
        let stale_html = runs_dir.join("report.html");
        std::fs::write(&stale_html, b"<html>stale</html>").unwrap();
        assert!(stale_html.exists());

        ReportGenerator::generate_all(runs_dir, &Cases::new(runs_dir, Vec::new())).unwrap();
        assert!(!stale_html.exists());
    }
}
