//! Case reports: `.gleon/runs/latest/cases/<name>.json`, the per-golden input of the gleon CLI.

#![forbid(unsafe_code)]

use std::{io::Write as _, time::Duration};

use gleon_engine::config::Zone;
use gleon_model::{
    case::{
        CASE_SCHEMA_VERSION, CASES_DIR, CandidateImage, CaseOutcome, CaseReport, CaseTimings,
        Comparison, GoldenImage, Metrics, RegionMetrics, Sha256Hex, Source, TestInfo,
    },
    fs::Durability,
    platform::PlatformConfig,
    tolerance::Tolerance,
};
use sha2::{Digest as _, Sha256};

use crate::session::{Integration, Record};

/// Everything a case report says about one comparison.
#[derive(Debug)]
pub struct Case<'a> {
    /// The golden's PNG bytes; `None` when it does not exist.
    pub golden: Option<&'a [u8]>,
    /// The candidate's PNG bytes.
    pub candidate: &'a [u8],
    /// Result of the comparison.
    pub outcome: CaseOutcome,
    /// The effective tolerance.
    pub tolerance: Tolerance,
    /// The effective masks.
    pub masks: &'a [Zone],
    /// Failure reason or error.
    pub message: Option<String>,
    /// Whole-image metrics, when a pixel comparison ran.
    pub metrics: Option<Metrics>,
    /// The whole comparison.
    pub total: Duration,
    /// Time spent in the engine, when it ran.
    pub native: Option<Duration>,
    /// The producing test, when known.
    pub test_name: Option<&'a str>,
}

/// Width and height from a PNG header, without decoding (absent when the header is not a PNG's).
fn png_size(bytes: &[u8]) -> Option<(u32, u32)> {
    const SIGNATURE: &[u8] = b"\x89PNG\r\n\x1a\n";
    let header = bytes.get(..24)?;
    if !header.starts_with(SIGNATURE) || &header[12..16] != b"IHDR" {
        return None;
    }
    let read = |at: usize| {
        u32::from_be_bytes([header[at], header[at + 1], header[at + 2], header[at + 3]])
    };
    Some((read(16), read(20)))
}

fn sha256(bytes: &[u8]) -> Sha256Hex {
    Sha256Hex::from_digest(&Sha256::digest(bytes).into())
}

/// `duration` in milliseconds with microsecond resolution.
pub fn millis(duration: Duration) -> f64 {
    #[expect(
        clippy::cast_precision_loss,
        reason = "durations are far below 2^52 microseconds"
    )]
    let micros = duration.as_micros() as f64;
    micros / 1000.0
}

/// Builds the report of `case`.
fn report(record: &Record, integration: &Integration, case: Case<'_>) -> CaseReport {
    let golden_size = case.golden.and_then(png_size);
    let candidate_size = png_size(case.candidate);
    CaseReport {
        schema_version: CASE_SCHEMA_VERSION,
        name: record.name.clone(),
        golden: GoldenImage {
            path: record.golden_path.clone(),
            sha256: case.golden.map(sha256),
            width: golden_size.map(|(width, _)| width),
            height: golden_size.map(|(_, height)| height),
        },
        candidate: CandidateImage {
            sha256: sha256(case.candidate),
            width: candidate_size.map(|(width, _)| width),
            height: candidate_size.map(|(_, height)| height),
        },
        source: Source {
            tool: integration.tool.clone(),
            tool_version: integration.tool_version.clone(),
            renderer: integration.renderer.clone(),
        },
        platform: PlatformConfig::host(),
        test: case.test_name.map(|name| TestInfo {
            name: Some(name.to_owned()),
        }),
        comparison: Comparison {
            tolerance: case.tolerance,
            masks: case.masks.to_vec(),
            policy_version: gleon_engine::ssim::POLICY_VERSION,
        },
        outcome: case.outcome,
        message: case.message,
        metrics: case.metrics,
        regions: case
            .metrics
            .map(RegionMetrics::whole_image)
            .into_iter()
            .collect(),
        timings_ms: CaseTimings {
            total: millis(case.total),
            native: case.native.map(millis),
        },
        recorded_at: chrono::Utc::now(),
    }
}

/// Writes the report of `case` for `record` (pretty JSON and a final newline), creating
/// `.gleon/.gitignore` (which ignores `runs/`) when it is missing.
///
/// Reports are regenerated by every run, so they are written atomically but not flushed to disk.
///
/// # Errors
/// Returns the warning to show when a file cannot be written.
pub fn write(record: &Record, integration: &Integration, case: Case<'_>) -> Result<(), String> {
    let file = record
        .workspace
        .gleon_dir()
        .join(CASES_DIR)
        .join(format!("{}.json", record.name));
    let report = report(record, integration, case);
    record
        .workspace
        .ensure_gitignore()
        .and_then(|()| {
            gleon_model::fs::write_atomically_with(&file, Durability::Atomic, |writer| {
                serde_json::to_writer_pretty(&mut *writer, &report)?;
                writer.write_all(b"\n")
            })
        })
        .map_err(|e| {
            format!(
                "gleon: cannot write the case report {}: {e}",
                file.display()
            )
        })
}

#[cfg(all(test, not(miri)))]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::pedantic,
    clippy::nursery,
    reason = "test code: panics are assertions, and pedantic/nursery style lints are not enforced in tests"
)]
mod tests {
    use super::*;

    #[test]
    fn test_png_size_reads_the_header_only() {
        let mut header = b"\x89PNG\r\n\x1a\n\0\0\0\x0dIHDR".to_vec();
        header.extend_from_slice(&100u32.to_be_bytes());
        header.extend_from_slice(&60u32.to_be_bytes());
        assert_eq!(png_size(&header), Some((100, 60)));
        assert_eq!(png_size(&header[..23]), None);
        let mut other = header.clone();
        other[12..16].copy_from_slice(b"IDAT");
        assert_eq!(png_size(&other), None);
        assert_eq!(png_size(&[7; 64]), None);
    }

    #[test]
    fn test_sha256_is_lowercase_hex() {
        assert_eq!(
            sha256(&[1, 2, 3]).as_str(),
            "039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81"
        );
    }
}
