/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef GLEON_FFI_H
#define GLEON_FFI_H
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Returns the contract version implemented by this library.
 */
uint32_t
gleon_ffi_abi_version (void);

/** \brief
 *  Opaque per-process state, owned by the caller until
 *  [`gleon_session_free`](crate::gleon_session_free).
 */
typedef struct GleonSession GleonSession_t;

/** \brief
 *  The scalars of one [`gleon_golden`](crate::gleon_golden) call. Read unaligned, so the
 *  caller may pass any buffer of its 48 bytes (Dart: `Struct.create` and `.address`).
 */
typedef struct GleonCall {
    /** \brief
     *  Pixel tolerance (`tolerance_kind` 2): the largest share of differing pixels.
     */
    double max_diff_ratio;

    /** \brief
     *  SSIM tolerance (`tolerance_kind` 3): the lowest local similarity.
     */
    double min_similarity;

    /** \brief
     *  SSIM tolerance (`tolerance_kind` 3): the color deviation beyond the envelope.
     */
    double color_tolerance;

    /** \brief
     *  The largest share of differing pixels in any tile of text, `[0, 1]`; NaN: the rule's.
     */
    double text_tolerance;

    /** \brief
     *  Width of a raw candidate (`candidate_format` 1).
     */
    uint32_t candidate_width;

    /** \brief
     *  Height of a raw candidate (`candidate_format` 1).
     */
    uint32_t candidate_height;

    /** \brief
     *  `0` compare, `1` update (write the golden; PNG only).
     */
    uint8_t mode;

    /** \brief
     *  `0` PNG bytes, `1` raw straight RGBA8 pixels.
     */
    uint8_t candidate_format;

    /** \brief
     *  `0` the `.gleon/gleon.yaml` rule, `1` exact, `2` pixel, `3` SSIM.
     */
    uint8_t tolerance_kind;
} GleonCall_t;

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** \brief
 *  Opaque texts of a call, owned by the caller until
 *  [`gleon_result_free`](crate::gleon_result_free).
 */
typedef struct GleonResult GleonResult_t;

/** \brief
 *  The verdict of a call and the texts to show, owned by `texts`; written unaligned to the
 *  caller's buffer of its 64 bytes.
 */
typedef struct GleonSummary {
    /** \brief
     *  `0` identical, `1` match, `2` mismatch, `3` dimension mismatch, `4` error,
     *  `5` updated, `6` missing golden.
     */
    uint8_t verdict;

    /** \brief
     *  For an error: `1` invalid input, `2` config, `3` I/O, `4` image, `5` internal;
     *  `0` otherwise.
     */
    uint8_t error_kind;

    /** \brief
     *  The test failure message (UTF-8); empty for a pass.
     */
    slice_ref_uint8_t message;

    /** \brief
     *  The console line to print; usually empty.
     */
    slice_ref_uint8_t console;

    /** \brief
     *  Warnings to print, one per line; usually empty.
     */
    slice_ref_uint8_t warning;

    /** \brief
     *  Owns the three texts until [`gleon_result_free`](crate::gleon_result_free); null when
     *  they are all empty.
     */
    GleonResult_t * texts;
} GleonSummary_t;

/** \brief
 *  Compares `candidate` against the golden file (`call.mode` 0), or writes it there (`mode` 1,
 *  update mode, PNG only), and returns the verdict with the texts to show.
 *
 *  `golden_path` is the shared golden. When the `.gleon/gleon.yaml` of its workspace names the
 *  `fallback_platform` the shared goldens were recorded on and this process runs on another,
 *  its own golden `<dir>/<os>-<arch>/<file>` is written and compared instead, and the shared one
 *  only while the own one does not exist.
 *
 *  The strings are `lengths_count` (4) UTF-8 strings packed into `strings`, `lengths` giving
 *  their byte lengths, in this order: `golden_path` (the file), `golden_uri` (the key shown in
 *  messages), `failures_dir` (the directory for failure artifacts, shown verbatim), `test_name`
 *  (the running test, may be empty).
 *
 *  The summary is written to `summary`. `call` holds the scalars ([`GleonCall`]): `candidate_format` `0` passes PNG bytes, `1` the raw
 *  straight (not premultiplied) RGBA8 pixels of a `candidate_width` x `candidate_height` capture
 *  (exactly `4 * width * height` bytes), which spares the integration encoding a PNG on every
 *  passing comparison; the call's tolerance is described at `call_tolerance`.
 *
 *  `mask_count` pixel masks `[x, y, width, height]` are at `masks`. `text_region_count` text
 *  regions `[x, y, width, height]` (candidate pixels) are at `text_regions`, compared in pixel
 *  and exact mode under `call.text_tolerance`: the largest share of differing pixels in any tile
 *  of text, `[0, 1]` (NaN: the rule's `text_tolerance`, else 0.05 against a golden of this
 *  platform and 1, so text never fails, against any other).
 *
 *  # Safety
 *  `call` must point to a readable [`GleonCall`] (any alignment) or be null, `summary` to a
 *  writable buffer of a [`GleonSummary`] (any alignment; null drops the summary). Each `(ptr, len)`
 *  pair must describe a readable buffer of `len` elements (bytes for `strings` and `candidate`,
 *  aligned `u32`s for `lengths`, `4 * mask_count` aligned `u32`s for `masks`,
 *  `4 * text_region_count` for `text_regions`), or be `(null, 0)`. All stay valid for the
 *  duration of this call.
 */
void
gleon_golden (
    GleonSession_t const * session,
    GleonCall_t const * call,
    GleonSummary_t * summary,
    uint8_t const * strings,
    size_t strings_len,
    uint32_t const * lengths,
    size_t lengths_count,
    uint8_t const * candidate,
    size_t candidate_len,
    uint32_t const * masks,
    size_t mask_count,
    uint32_t const * text_regions,
    size_t text_region_count);

/** \brief
 *  Releases the `texts` of a [`GleonSummary`]. Passing null is a no-op.
 */
void
gleon_result_free (
    GleonResult_t * result);

/** \brief
 *  Releases a session. Passing null is a no-op.
 */
void
gleon_session_free (
    GleonSession_t * session);

/** \brief
 *  Creates the session of a test process.
 *
 *  `flags` combines [`SESSION_FIND_WORKSPACE`] and [`SESSION_ENV`]. The strings are
 *  `lengths_count` (9) UTF-8 strings packed into `strings`, `lengths` giving their byte
 *  lengths, in this order:
 *  1. to 3. `metrics_env`, `artifacts_env`, `run_id_env`: with [`SESSION_ENV`] the values of
 *  `GLEON_METRICS` (metrics on or off), `GLEON_ARTIFACTS_DIR` (the artifacts directory of
 *  every workspace) and `GLEON_RUN_ID` (the run in case reports), empty for unset; without
 *  it they are ignored and the process environment is read;
 *  4. `tool`, 5. `tool_version`: the integration in case reports (`gleon_flutter`, `0.1.0`);
 *  6. `renderer`: e.g. `flutter-3.47.5`, may be empty;
 *  7. to 9. the file name patterns of the failure artifacts of the golden, the candidate and the
 *  diff; each contains `{name}` (the golden's file name without extension), e.g.
 *  `{name}_masterImage.png`.
 *
 *  Invalid input, or an invalid value of one of the variables, yields a session whose every call
 *  fails with the reason.
 *
 *  # Safety
 *  `(strings, strings_len)` must describe `strings_len` readable bytes and `(lengths,
 *  lengths_count)` `lengths_count` aligned `u32`s (or be `(null, 0)`), valid for the duration of
 *  this call.
 */
GleonSession_t *
gleon_session_new (
    uint32_t flags,
    uint8_t const * strings,
    size_t strings_len,
    uint32_t const * lengths,
    size_t lengths_count);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* GLEON_FFI_H */
